---
- hosts: localhost
  tasks:
    - name: ami creation through ec2
      ec2_ami:
        instance_id: i-013ec4c630dfae7b2
        region: us-west-1
        wait: yes
        name: adulami
        tags:
          Name: abdulami
          Service: TestService
