---
- hosts: localhost
  sudo: yes
  tasks:
    - name: ami creation through ec2
      ec2_ami:
        instance_id: i-03d1c57146c1859eb
        wait: yes
        name: adulami
        tags:
          Name: abdulami
          Service: TestService
